### PR TITLE
add basic support for bitsy games

### PR DESCRIPTION
**Pull request by wyatthilde**

### CODE REVIEW

**Comment by arkin0x** [comment]
@wyatthilde Awesome! 😃 Have you tested this out locally? Were you able to publish a game and play it?

**Comment by wyatthilde** [comment]
Yes! I was able to publish and play right away and also able to find it via identifier as well! On Apr 1, 2024, at 8:25 AM, arkinox ***@***.***> wrote:﻿
@wyatthilde Awesome! 😃 Have you tested this out locally? Were you able to publish a game and play it?

**Comment by arkin0x** [comment]
@wyatthilde hey, when I test it out it doesn't seem to work. I am using this game nevent:

note1fgwnhu6nadpgnj5902qh2exvdfvaqyzgps49ypzpttg6kur6gv9qt26q7j

I'm using it on the Vercel dev link above that has your PR:

https://vercel.live/open-feedback/crashglow-git-fork-wyatthilde-bitsy-ga-33c6f7-arkinoxs-projects.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

Can you take a look at that?

Sorry but I don't feel comfortable merging until I see it working. Also I am wondering why published bitsy games don't show up in the homepage feed?

**Comment by arkin0x** [comment]
Used this gameID to test: 8f417b4e-c835-47c2-8eaf-9d2c455334e2

**Pull request merged**
